### ISSUE TITLE
Call callback which already called in create product

### ISSUE THREAD

**Issue by Rastopyr** [winnlab/Agusha#17]
```
C:\Users\Mari\Desktop\Agusha\node_modules\async\lib\async.js:30
            if (called) throw new Error("Callback was already called.");
                              ^
Error: Callback was already called.
  at C:\Users\Mari\Desktop\Agusha\node_modules\async\lib\async.js:30:31
  at C:\Users\Mari\Desktop\Agusha\node_modules\async\lib\async.js:251:21
  at C:\Users\Mari\Desktop\Agusha\node_modules\async\lib\async.js:575:34
  at Function.app.render (C:\Users\Mari\Desktop\Agusha\node_modules\express\lib\
application.js:513:5)
  at ServerResponse.res.render (C:\Users\Mari\Desktop\Agusha\node_modules\expres
s\lib\response.js:817:7)
  at async.parallel.node_env (C:\Users\Mari\Desktop\Agusha\lib\view.coffee:18:8)
```

**Comment by mshekera** [comment]
Напрямую связано с возникновением ошибки при рендеринге ( #16 в частности), само по себе никогда не возникало. В коде явных "замкнытх кругов" нет. Возможно конкретно сообщение об ошибке #17 вероятно можно исправить при помощи error handling типа try..catch или какого-то другого.
